spring:
  datasource:
    url: jdbc:postgresql://postgres:znFUIKkWOYrwVWhOpiKshMKGXBkawbAa@autorack.proxy.rlwy.net:49667/railway
    username: ${PGUSER}
    password: ${PGPASSWORD}
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
